name: Build
description: Build and install dependencies
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Task
      uses: arduino/setup-task@v2

    - name: Build Docker containers and install dependencies
      shell: bash
      run: task install

    - name: Start Docker containers
      shell: bash
      run: task start
