services:

  reverse-proxy:
    build: ./services/traefik
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  nginx:
    build: ./services/nginx
    restart: unless-stopped
    labels:
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
    volumes:
      - "./apps/api:/usr/src/app"

  php:
    build:
      context: ./apps/api
      dockerfile: ../../services/php/Dockerfile
    environment:
      - PHP_CS_FIXER_IGNORE_ENV=1
    volumes:
      - "./apps/api:/usr/src/app"
    restart: on-failure
    depends_on:
      - mysql

  web:
    build:
      context: ./apps/web
      dockerfile: ../../services/web/Dockerfile
    volumes:
      - "./apps/web:/usr/src/app"
    restart: on-failure
    labels:
    - "traefik.http.routers.web.rule=Host(`localhost`)"

  mysql:
    build: ./services/mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
