services:

  reverse-proxy:
    image: traefik:v3.3
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  web:
    build:
      context: ./apps/web
      dockerfile: ../../docker/web/Dockerfile
    volumes:
      - "./apps/web:/usr/src/app"
    restart: on-failure
    labels:
    - "traefik.http.routers.web.rule=Host(`localhost`)"

  php:
    build:
      context: ./apps/api
      dockerfile: ../../docker/php/Dockerfile
    volumes:
      - "./apps/api:/usr/src/app"
    restart: on-failure
    depends_on:
      - mysql

  nginx:
    build:
      context: ./apps/nginx
      dockerfile: ../../docker/nginx/Dockerfile
    restart: on-failure
    volumes:
      - "./apps/api:/usr/src/app"
    depends_on:
      - php
    labels:
    - "traefik.http.routers.api.rule=Host(`api.localhost`)"

  mysql:
    image: mysql:8.4.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
