version: '3'

includes:
  api: ./tasks/api.yml
  web: ./tasks/web.yml

tasks:
  install:
    cmds:
      - cp apps/api/.env.dist apps/api/.env
      - docker compose build
      - docker compose run --rm php composer install
      - docker compose run --rm web yarn install
      - docker compose run --rm web yarn build

  start:
    cmds:
      - docker compose up -d

  stop:
    cmds:
      - docker compose down
