version: '3'

tasks:
  install:
    cmds:
      - cp apps/api/.env.dist apps/api/.env
      - cp apps/web/.env.dist apps/web/.env
      - docker compose build

  start:
    cmds:
      - docker compose up -d

  stop:
    cmds:
      - docker compose down
