version: '3'

tasks:
  install:
    cmds:
      - cp apps/api/.env.dist apps/api/.env
      - docker compose build
      - docker compose run --rm php composer install
      - docker compose run --rm web yarn install
      - docker compose run --rm web yarn build

  start:
    cmds:
      - docker compose up -d

  stop:
    cmds:
      - docker compose down

  phpstan:
    cmds:
      - docker compose run --rm php vendor/bin/phpstan

  cs-fix:
    cmds:
      - docker compose run --rm php vendor/bin/php-cs-fixer fix

  cs-check:
    cmds:
      - docker compose run --rm php vendor/bin/php-cs-fixer fix --dry-run --diff

  lint-fix:
    cmds:
      - docker compose run --rm web yarn lint --fix

  lint-check:
    cmds:
      - docker compose run --rm web yarn lint

  test:
    cmds:
      - docker compose run --rm web yarn test
