name: api
run-name: ${{ github.event_name }}-${{ github.ref_name }}
on:
  push:
    paths:
      - 'api/**'
      - '.github/workflows/api.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'api/**'
      - '.github/workflows/api.yml'
    branches:
      - main

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.should_skip.outputs.should_skip }}
    steps:
      - name: Check if the commit message contains [skip ci]
        id: should_skip
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"[skip ci]"* ]]; then
            echo "should_skip=true" >> $GITHUB_ENV
          else
            echo "should_skip=false" >> $GITHUB_ENV
          fi

  lint_and_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Run api static analysis
        run: task api:static-analysis

      - name: Run api lint check
        run: task api:lint-check

      - name: Run api tests
        run: task api:test
